package Peaks::Kloke;

$Peaks::Kloke::Peaks = [{ name => "Abiel Peak", elevation => 5365, quads => "Lost Lake", },
	     { name => "K9", elevation => 6242, quads => "Stevens Pass", },
	     { name => "Point 6131", elevation => 6131, quads => "Wenatchee Lake", },
	     { name => "Acorn Mountain", elevation => 4724, quads => "Damnation Peak, Marblemount", },
	     { name => "Anderson Butte", elevation => 5700, quads => "Bacon Peak", },
	     { name => "Arrowhead Mountain", elevation => 6030, quads => "Wenatchee Lake", },
	     { name => "Avalanche Mountain", elevation => 5360, quads => "Snoqualmie Pass", },
	     { name => "Aw Peak", elevation => 4720, quads => "Gee Point", },
	     { name => "Bald Mountain", elevation => 5481, quads => "Glacier", },
	     { name => "Bald Mountain", elevation => 4795, quads => "Silverton", },
	     { name => "Bald Mountain", elevation => 5408, quads => "Sauk Mountain", },
	     { name => "Bald Mountain", elevation => 4550, quads => "Cavanaugh Creek", },
	     { name => "Bandera Mountain", elevation => 5240, quads => "Bandera", },
	     { name => "Baring Mountain", elevation => 6215, quads => "Baring", },
	     { name => "Barometer Mountain", elevation => 5770, quads => "Shuksan Arm", },
	     { name => "Bearscout Peak", elevation => 5200, quads => "Snoqualmie Pass, Lost Lake", },
	     { name => "Beaver Peak", elevation => 5085, quads => "Silverton, Glacier Peak", },
	     { name => "Beckler Peak", elevation => 5062, quads => "Skykomish", },
	     { name => "Bessemer Mountain", elevation => 5100, quads => "Lake Philippa", },
	     { name => "Big Deer Peak", elevation => 4311, quads => "Day Lake, Oso", },
	     { name => "Bryant Peak", elevation => 5801, quads => "Snoqualmie Pass", },
	     { name => "Canoe Peak", elevation => 5706, quads => "Grotto", },
	     { name => "Kayak Peak", elevation => 5743, quads => "Grotto", },
	     { name => "Cascade Mountain, North", elevation => 5553, quads => "Grotto", },
	     { name => "Cathedral Crag", elevation => 5200, quads => "Baker Pass", },
	     { name => "Mount Catherine", elevation => 5052, quads => "Snoqualmie Pass, Lost Lake", },
	     { name => "Chair Peak", elevation => 6238, quads => "Snoqualmie Pass", },
	     { name => "Change Peak", elevation => 4360, quads => "Chester Morse Lake", },
	     { name => "Church Mountain", elevation => 6315, quads => "Bear paw, Glacier", },
	     { name => "West Church Benchmark", elevation => 5610, quads => "Bear Paw, Glacier", },
	     { name => "Cleveland Mountain", elevation => 5301, quads => "Grotto", },
	     { name => "Conglomerate Point", elevation => 5200, quads => "Baring", },
	     { name => "Cousins Peak", elevation => 6700, quads => "Diablo Dam", },
	     { name => "Cowboy Mountain", quads => "Stevens Pass, Scenic", },
	     { name => "Big Chief Mountain", quads => "Stevens Pass, Scenic", },
	     { name => "Crosby Mountain", elevation => 5533, quads => "Grotto", },
	     { name => "Damnation Peak", elevation => 5635, quads => "Mount Triumph", },
	     { name => "Mount Defiance", elevation => 5584, quads => "Bandera", },
	     { name => "Del Campo Peak", elevation => 6610, quads => "Monte Cristo", },
	     { name => "Denny Mountain", elevation => 5520, quads => "Snoqualmie Pass", },
	     { name => "Devils Peak", elevation => 5453, quads => "Silverton", },
	     { name => "Mount Dickerman", elevation => 5723, quads => "Bedal", },
	     { name => "Diobsud Buttes South", elevation => 5871, quads => "Marblemount", },
	     { name => "Dock Butte", elevation => 5210, quads => "Baker Pass", },
	     { name => "Duke of Kent", elevation => 4800, quads => "Bandera, Chester Morse Lake", },
	     { name => "Duchess of Kent", elevation => 4703, quads => "Bandera, Chester Morse Lake", },
	     { name => "Eagle's Perch", elevation => 5120, quads => "Verlot", },
	     { name => "Eagle's Perch Towers", elevation => , quads => "Verlot", },
	     { name => "Eagle Rock", elevation => 5612, quads => "Evergreen Mountain", },
	     { name => "Englebright Peak", elevation => 5163, quads => "Baker Pass", },
	     { name => "Evergreen Mountain", elevation => 5587, quads => "Evergreen Mountain", },
	     { name => "Excelsior Mountain", elevation => 4832, quads => "Blanca Lake", },
	     { name => "Exclamation Point", elevation => 4725, quads => "Gee Point", },
	     { name => "Mount Fernow", elevation => 6190, quads => "Skykomish, Captain Point, Scenic", },
	     { name => "Finney Peak", elevation => 5083, quads => "Finney Peak", },
	     { name => "Floating Rock", elevation => 5174, quads => "Snoqualmie Lake", },
	     { name => "Frog Mountain", elevation => 4800, quads => "Blanca Lake", },
	     { name => "Mount Gardner", elevation => 4453, quads => "Bandera, Findley Lake", },
	     { name => "Gee Peak", elevation => 5050, quads => "Gee Point", },
	     { name => "Gee Point", elevation => 4974, quads => "Gee Point", },
	     { name => "Goat Mountain", elevation => 4778, quads => "Grandy Lake", },
	     { name => "Gosh Peak", elevation => 4800, quads => "Gee Point", },
	     { name => "Golly Peak", elevation => 5000, quads => "Gee Point", },
	     { name => "Anaconda Peak", elevation => 5050, quads => "Silverton", },
	     { name => "Granite Mountain", elevation => 5629, quads => "Snoqualmie Pass", },
	     { name => "Green Mountain", elevation => 4824, quads => "Mount Si, Chester Morse Lake", },
	     { name => "Green Mountain", elevation => 6500, quads => "Downey Mountain", },
	     { name => "Greider Peak", elevation => 4838, quads => "Mount Stickney", },
	     { name => "Groat Mountain", elevation => 5581, quads => "", },
	     { name => "Klinger Ridge", elevation => 5620, quads => "Grotto", },
	     { name => "Guye Peak", elevation => 5168, quads => "Snoqualmie Pass", },
	     { name => "Hall Peak", elevation => 5452, quads => "Silverton", },
	     { name => "Helen Buttes North", elevation => 5513, quads => "Marblemount", },
	     { name => "Helena Peak", elevation => 5401, quads => "Helena Ridge", },
	     { name => "Mount Herman", elevation => 6285, quads => "Shuksan Arm", },
	     { name => "Mount Higgins", elevation => 5190, quads => "Mount Higgins, Fortson", },
	     { name => "Skadulgwas Peak", elevation => 4960, quads => "Mount Higgins", },
	     { name => "Sexagenarian Peak", elevation => 4849, quads => "Mount Higgins", },
	     { name => "Humpback Mountain", elevation => 5174, quads => "Snoqualmie Pass, Lost Lake", },
	     { name => "Iron Mountain", elevation => 4793, quads => "Day Lake", },
	     { name => "Iron Mountain", elevation => 5241, quads => "Baring", },
	     { name => "Jackman Peak", elevation => 5205, quads => "Sauk Mountain", },
	     { name => "Jim Hill Mountain", elevation => 6765, quads => "Wenatchee Lake", },
	     { name => "Mount Josephine", elevation => 3956, quads => "Hamilton", },
	     { name => "Kendall Peak", elevation => 5784, quads => "Snoqualmie Pass", },
	     { name => "Mount Kent", elevation => 5087, quads => "Bandera, Chester Morse Lake", },
	     { name => "Lewis Peak", elevation => 5608, quads => "Bedal", },
	     { name => "Lichtenberg Mountain", elevation => 5844, quads => "Labyrinth Mountain", },
	     { name => "Little Deer Peak", elevation => 4400, quads => "Day Lake, Oso", },
	     { name => "Little Saint Helens", elevation => 4582, quads => "Bandera, Findley Lake", },
	     { name => "Long Mountain", elevation => 5113, quads => "Silverton", },
	     { name => "Long Mountain - East Peak", elevation => 4829, quads => "Silverton", },
	     { name => "Lookout Mountain", elevation => 5719, quads => "Big Devil Peak", },
	     { name => "Loomis Mountain", elevation => 5598, quads => "Baker Pass", },
	     { name => "Wellman & Huntoon Crags", elevation => 5500, quads => "Baker Pass", },
	     { name => "Lundin Peak", elevation => 6057, quads => "Snoqualmie Pass", },
	     { name => "Mailbox Peak", elevation => 4926, quads => "Bandera, Chester Morse Lake", },
	     { name => "Marble Peak", elevation => 5111, quads => "Silverton", },
	     { name => "Mazama Dome", elevation => 5842, quads => "Shuksan Arm", },
	     { name => "McClellan Butte", elevation => 5162, quads => "Chester Morse Lake", },
	     { name => "Mineral Butte", elevation => 5255, quads => "Monte Cristo", },
	     { name => "National Peak", elevation => 5630, quads => "Monte Cristo", },
	     { name => "Nina", elevation => 4695, quads => "Mount Index, Mount Stickney", },
	     { name => "Pinta", elevation => 4760, quads => "Mount Index, Mount Stickney", },
	     { name => "Zekes Peak", elevation => 4865, quads => "Mount Index, Mount Stickney", },
	     { name => "Oakes Peak", elevation => 5696, quads => "Damnation Peak", },
	     { name => "Palmer Mountain", elevation => 5043, quads => "Grotto", },
	     { name => "Park Butte", elevation => 5471, quads => "Baker Pass", },
	     { name => "Point 4962", elevation => 4962, quads => "Snoqualmie Lake", },
	     { name => "Point 6131", elevation => 6131, quads => "Wenatchee Lake", },
	     { name => "Mount Persis", elevation => 5452, quads => "Index", },
	     { name => "Mount Phelps", elevation => 5540, quads => "Mount Phelps", },
	     { name => "Mount Pilchuck", elevation => 5324, quads => "Verlot", },
	     { name => "The Pulpit", elevation => 4440, quads => "Lake Philippa", },
	     { name => "Point 5598", elevation => 5598, quads => "Big Snow Mountain", },
# Near Lumiere Ridge:
	     { name => "Poweroutage Peak", elevation => 5500, quads => "Stevens Pass", },
	     { name => "Prairie Mountain", elevation => 5678, quads => "Prairie Mountain", },
	     { name => "Pratt Mountain", elevation => 5099, quads => "Bandera Mountain", },
	     { name => "Quartz Mountain", elevation => 4641, quads => "Lake Philippa", },
	     { name => "Razorback Mountain", elevation => 6110, quads => "Big Devil Peak, Snowking Mountain", },
	     { name => "Red Mountain", elevation => 5890, quads => "Snoqualmie Pass", },
	     { name => "Red Rock Mountain", elevation => 4200, quads => "Hamilton", },
	     { name => "Revolution Peak", elevation => 5454, quads => "Bandera", },
	     { name => "Mount Ross", elevation => 6052, quads => "Mount Triumph, Diablo Dam", },
	     { name => "Round Mountain", elevation => 5320, quads => "Fortson, Mount Higgins", },
	     { name => "Sauk Mountain", elevation => 5537, quads => "Sauk Mountain", },
	     { name => "Mount Sawyer", elevation => 5501, quads => "Scenic, Skykomish", },
	     { name => "Silver Eagle Peak", elevation => 6259, quads => "Skykomish, Big Snow Mountain", },
	     { name => "Silver Peak", elevation => 5600, quads => "Snoqualmie Pass, Lost Lake", },
	     { name => "Mount Si", elevation => 4167, quads => "Mount Si", },
	     { name => "Sky Mountain", elevation => 5482, quads => "Labyrinth Mountain, Stevens Pass", },
	     { name => "Tye Peak", elevation => 5476, quads => "Labyrinth Mountain, Stevens Pass", },
	     { name => "Slate Mountain", elevation => 6250, quads => "Shuksan Arm", },
	     { name => "Snoqualmie Mountain", elevation => 6385, quads => "Snoqualmie Pass", },
	     { name => "Sorcery Mountain", elevation => 5273, quads => "Snoqualmie Lake", },
	     { name => "Sourdough Mountain", elevation => 5985, quads => "Mount Prophet", },
	     { name => "Spring Mountain", elevation => 5770, quads => "Sloan Peak", },
	     { name => "Static Peak", elevation => 5100, quads => "Mount Stickney", },
	     { name => "Table Mountain", elevation =>5742, quads => "Shuksan Arm", },
	     { name => "Mazama Dome", elevation => 5842, quads => "Shuksan Arm", },
	     { name => "Tinkham Peak", elevation => 5356, quads => "Snoqualmie Pass, Lost Lake", },
	     { name => "Toil Peak", elevation => 5128, quads => "Blanca Lake", },
	     { name => "Double Toil Peak", elevation => 5427, quads => "Blanca Lake", },
	     { name => "The Tooth", elevation => 5604, quads => "Snoqualmie Pass", },
	     { name => "Townsend Mountain", elevation => 5936, quads => "Baring", },
	     { name => "Trappers Peak", elevation => 5964, quads => "Mount Triumph", },
	     { name => "Troublesome Mountain", elevation => 5433, quads => "Monte Cristo, Blanca Lake", },
	     { name => "Twin Peaks South", elevation => 5325, quads => "Lake Phillipa, Devils Slide, Mount Phelps", },
	     { name => "Viking Horns", elevation => 4800, quads => "Silverton", },
	     { name => "Mount Washington", elevation => 4400, quads => "Chester Morse Lake", },
	     { name => "Washington Monument", elevation => 4811, quads => "Baker Pass", },
	     { name => "Web Mountain", elevation => 5335, quads => "Bandera", },
	     { name => "Welker Peak", elevation => 5587, quads => "Lake Shannon", },
	     { name => "West Cady Ridge", elevation => 4800, quads => "Benchmark Mountain, Blanca Lake", },
	     { name => "Whim Peak", elevation => 4800, quads => "Gee Point", },
	     { name => "Whiz Peak", elevation => 5080, quads => "Gee Point", },
# South of Wobegon Peak:
	     { name => "Widgit Peak", elevation => 5300, quads => "Bacon Peak", },
	     { name => "Windy Mountain", elevation => 5386, quads => "Scenic", },
	     { name => "Wobegon Peak", elevation => 5117, quads => "Bacon Peak", },
	    ];
